### ISSUE TITLE
Support for more metadata fields?

### ISSUE THREAD

**Issue by mike-engel** [mz2/Carpaccio#10]
First off, thanks for making this project! It's been really helpful for loading and grabbing thumbnails of photos, especially RAW photos!

I'm wondering if there are plans to add more metadata fields in the future? Ones that come to mind are lens info, exif data like Title, Description, etc. If this should be in user-land, maybe just exposing the metadata dict in either the `ImageLoader` or `ImageMetadata` structs?

I'm happy to take a first pass at a PR, but wanted to check if there was a reason they were left out from the project.

**Comment by markuspiipari** [comment]
Sure, a PR for lens info and EXIF title & description will be welcome.

The reason `ImageMetadata` is like it now is, is that it is intended to encapsulate a very basic set of essential image metadata in a Swift type, not need to examine or keep around the full set of metadata dictionaries you can get from Image I/O.
