### ISSUE TITLE
ImageMetadata loaded with loadFullSizeImage doesn't contain valuable information

### ISSUE THREAD

**Issue by MrZoidberg** [mz2/Carpaccio#3]
ImageMetadata doesn't contain valuable information when you call
`loadFullSizeImage(options: FullSizedImageLoadingOptions,
                                  handler: @escaping PresentableImageHandler,
                                  errorHandler: @escaping ImageLoadingErrorHandler)`

because the handler is run with empty ImageMetadata: `handler(nonNilNakedImage, ImageMetadata(nativeSize: nonNilNakedImage.size))`

I think this should be changed to `handler(nonNilNakedImage, metadata)`

**Comment by mz2** [comment]
Oops, that's true, and your fix looks correct as well. @markuspiipari can you check this through as well and merge if you and the CI are happy with the tests?

**Comment by markuspiipari** [comment]
Looks great to me, merged with joy! Thanks, @MrZoidberg.

**Comment by MrZoidberg** [comment]
Closing this issue as PR is merged.
