### ISSUE TITLE
Cannot select "Carpaccio.xcodeproj"  in "Embedded Binaries" 

### ISSUE THREAD

**Issue by Geeta1993** [mz2/Carpaccio#8]
Couldn't select "Carpaccio.xcodeproj"  in "Embedded Binaries" so i added "Carpaccio.frameworkiOS".
When i added code given in the document to process RAW file it throws error ---> Use of unresolved identifier 'RAWImageLoader'.
Help me to solve this problem.
Thanks!!

**Comment by mz2** [comment]
Preetty sure this has been resolved since, nomenclature changed and CI added.
